export enum OrderStatus {
  PENDING    = 'PENDING',
  CONFIRMED  = 'CONFIRMED',
  PREPARING  = 'PREPARING',
  READY      = 'READY',
  SERVED     = 'SERVED',
  COMPLETED  = 'COMPLETED',
  CANCELLED  = 'CANCELLED',
}
